name: Serverless Dry Deploy
description:
  An action to perform a serverless package to ensure the deployment is successful.

inputs:
  stage:
    description: "Deployment stage"
    required: true
  region:
    description: "AWS Region"
    required: true

runs:
  using: "composite"
  steps:
    - name: Serverless Package
      run: make dry-deploy STAGE=${{ inputs.stage }} REGION=${{ inputs.region }}
      shell: bash
