name: Configure CI
description: Configures the CI environment, downloads go.mod, and installs test tools

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      shell: bash
    - name: Configure Git and Dependencies
      run: make configure-ci
      shell: bash
