name: Serverless Deploy
description:
  An action to deploy a serverless template file to a specified region and stage

inputs:
  stage:
    description: "Deployment stage"
    required: true
  region:
    description: "AWS Region"
    required: true
  role:
    description: "AWS role to assume"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.role }}
        aws-region: ${{ inputs.region }}

    - name: serverless deploy
      uses: serverless/github-action@v3.1
      with:
        args: deploy --stage ${{ inputs.stage }} --region ${{ inputs.region }}
