name: CI-CD Dev Branch CF Stack Cleanup
on:
  workflow_dispatch:
  workflow_call:
  delete:

jobs:
  delete-dev-stacks:
    name: A job to clean up a dev deployment
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    environment: development
    strategy:
      matrix:
        region: [us-east-2]
    steps:
      - uses: actions/checkout@v3
    permissions:
      id-token: write
      contents: read
