name: CI-CD Main
run-name: Initiated by ${{ github.actor }}
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - "main"

concurrency:
  # New commit on branch queued if old workflow is running
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-to-alpha:
    name: Serverless Deploy alpha
    runs-on: ubuntu-latest
    environment: alpha
    strategy:
      matrix:
        region: [us-east-2]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/configure-ci
      - uses: ./.github/actions/unit-test-go
      - uses: ./.github/actions/build-go
      # - uses: ./.github/actions/sls-deploy
      #   with:
      #     stage: alpha
      #     region: ${{ matrix.region }}
      #     role: "example-role"
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
